### ISSUE TITLE
[Collector] Configured snapshot interval doesn’t change after collector restart

### ISSUE THREAD

**Issue by mhaenggi** [denkbar/djigger#51] opened 2016-04-27 06:44 UTC
For some collector we configured 5sec. Later we changed them to 10sec. But according to the log these changes didn’t affect anything. We still have the collectors in a 5sec interval.
Current used collector version: 1.4.1
[interval_issue.zip](https://github.com/denkbar/djigger/files/238051/interval_issue.zip)

**Comment by jeromecomte** [comment] 2016-04-27 07:02
When did you restart the collector process? I don't find any sign of restart in the logs you've provided

**Comment by mhaenggi** [comment] 2016-04-28 05:29
[collector_log.zip](https://github.com/denkbar/djigger/files/239847/collector_log.zip)
See restart at 2016-04-26 15:06:35
About 75 Collectors were started. All with 10sec. If you pick one host, you'll see the 5sec interval of connecting:
2016-04-26 15:06:59,233 INFO [Timer-13] ... Creating JMX connection to H50AB20:18402
2016-04-26 15:07:04,233 INFO [Timer-13] ... Creating JMX connection to H50AB20:18402
2016-04-26 15:07:09,233 INFO [Timer-13] ... Creating JMX connection to H50AB20:18402
2016-04-26 15:07:24,233 INFO [Timer-13] ... Creating JMX connection to H50AB20:18402
2016-04-26 15:07:14,233 INFO [Timer-13] ... Creating JMX connection to H50AB20:18402
2016-04-26 15:07:19,233 INFO [Timer-13] ... Creating JMX connection to H50AB20:18402

**Comment by jeromecomte** [comment] 2016-04-28 05:37
Thanks for the Feedback. I ll look at it today.
Am 28.04.2016 7:29 Vorm. schrieb "mhaenggi" <notifications@github.com>:

**Comment by jeromecomte** [comment] 2016-04-28 07:51
Hi Michel,

The log entries " INFO [Timer-13] ... Creating JMX connection ..." are generated by the auto-reconnect timer which has an hardcoded rate of 5s. This is isn't not related to the sampling rate that you configure in your Connections.csv.

If you want to check the sampling rate just zoom into the thread-selection frame and you should see the individual dumps scheduled at the configured rate.

See Façade.java line 67: 

		if(autoReconnect) {
			timer = new Timer();
			timer.schedule(new TimerTask() {
				@Override
				public void run() {
					try {
						if(!isConnected()) {
								connect();
								restoreSession();
						}
					} catch (Exception e) {
						logger.debug("Unable to reconnect facade " + properties.toString(), e);
					}
				}
				
			}, 10000, **5000**);
		}

**Comment by dcransac** [comment] 2016-05-12 11:29
This is correct. Root cause of the misinterpretation has been further described and addressed in issue #52

**Closed by dcransac** 2016-05-12 11:29 UTC
